export { default as winterBg1 } from './winter-bg1.jpg'
export { default as winterBg2 } from './winter-bg2.jpg'
export { default as winterBg3 } from './winter-bg3.jpg'
export { default as errorImage } from './error.png'
export { default as testBG } from './testBG.jpg'
